<li class="nav-item"><a class="nav-link py-1" href="index"><i class="fas fa-tachometer-alt"></i> <span class="nav-link-text">Dashboard</span></a></li>
<li class="nav-item"><a class="nav-link py-1" href="admin"><i class="fas fa-user-alt"></i> <span class="nav-link-text">Admin</span></a></li>
<li class="nav-item"><a class="nav-link py-1" href="album"><i class="far fa-images"></i> <span class="nav-link-text">Album</span></a></li>
<li class="nav-item"><a class="nav-link py-1" href="categories"><i class="fas fa-boxes"></i> <span class="nav-link-text">Categories</span></a></li>
<li class="nav-item"><a class="nav-link py-1" href="contact"><i class="far fa-address-card"></i> <span class="nav-link-text">Contact</span></a></li>
<li class="nav-item"><a class="nav-link py-1" href="contents"><i class="fas fa-pencil-alt"></i> <span class="nav-link-text">Contents</span></a></li>
<li class="nav-item"><a class="nav-link py-1" href="events"><i class="far fa-calendar-check"></i> <span class="nav-link-text">Events</span></a></li>
<li class="nav-item"><a class="nav-link py-1" href="photos"><i class="fas fa-camera"></i> <span class="nav-link-text">Photos</span></a></li>
<li class="nav-item"><a class="nav-link py-1" href="sub_categories"><i class="fas fa-boxes"></i> <span class="nav-link-text">Sub_categories</span></a></li>
<li class="nav-item"><a class="nav-link py-1" href="youtube_videos"><i class="fab fa-youtube"></i> <span class="nav-link-text">Youtube_videos</span></a></li>